name: Run tests
on: [push]
jobs:
  test:
    name: Test on Ubuntu 18.04
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: apt update
        run: sudo apt update
      - name: Run tests
        run: cd tests && bash run_tests.sh
